# Make sure to copy id to target server using ssh-copy-id <AD_ID>@<Target_Server>
---
- hosts: [dbservers]
  become: yes
  remote_user: AD_ID
  become_user: root
  tasks:
   - name: copy rpm files from control server to target server /tmp directory
     copy:
      src: "{{ item }}"
      dest: /tmp/
     with_fileglob:
      - /home/AD_ID/software/mysql8ee/*.rpm


Note: 

# Make sure to have ssh-id copied to target, if not use following command to copy ssh-id at target/
# Execute following command from Ansible Tower / Ansieble machine.

$ssh-copy-id <AD ID>@<target_IP_address>

Execute ansible-playbook as follows, if you are at directory /home/AD_ID/software/mysql8ee/
$ansible-playbook CopyRpm.yml *.rpm 

If ssh key is not generated on Target Server Or Target Server is re-configured then execute following steps

01. Generate ssh key on Target Server using command ssh-keygen
02. Copy key from Target Server /home/<AD_ID>/.ssh/.id_rsa.pub
03. Paste key from step 2 to Ansible Server /home/<AD_Name>/.ssh/known_hosts
04. From Ansible Server execute $ssh-copy-id <AD ID>@<target_IP_address>

If Server is re-configured or OS is -re-installed then follow following step and above steps

01. From Ansible Server /home/<AD_Name>/.ssh/known_hosts remove the key for the Target Server reconfigured.

###
### Copy files with multiple extension
###
### If you want to copy files with multiple extenstion then play book will looks like follows

# Make sure to copy id to target server using ssh-copy-id <AD_ID>@<Target_Server>
---
- hosts: [dbservers]
  become: yes
  remote_user: AD_ID
  become_user: root
  tasks:
   - name: copy rpm files from control server to target server /tmp directory
     copy:
      src: "{{ item }}"
      dest: /tmp/
     with_fileglob:
      - /home/AD_ID/software/mysql8ee/*.rpm
      - /home/AD_ID/software/mysql8ee/*.bin
