# Make sure to copy id to target server using ssh-copy-id <AD_ID>@<Target_Server>
---
- hosts: [dbservers]
  become: yes
  remote_user: AD_ID
  become_user: root
  tasks:
   - name: copy rpm files from control server to target server /tmp directory
     copy:
      src: "{{ item }}"
      dest: /tmp/
     with_fileglob:
      - /home/AD_ID/software/mysql8ee/*.rpm


Note: 

Make sure to have ssh-id copied to target, if not use following command to copy ssh-id at target/

$ssh-copy-id <AD ID>@<target_IP_address>

Execute ansible-playbook as follows, if you are at directory /home/AD_ID/software/mysql8ee/
$ansible-playbook CopyRpm.yml *.rpm 

If ssh key is not generated on Target Server Or Target Server is re-configured then execute folloiwng steps

01. Generate ssh key on Target Server using following command ssh-keygen
02. Copy key from /home/<AD_ID>/.ssh/.id_rsa.pub
03. Paste key from step 2 to Ansible Server /home/<AD_Name>/.ssh/known_hosts
04. From Ansible Server execute $ssh-copy-id <AD ID>@<target_IP_address>
