---
- hosts: [dbservers]
  become: yes
  remote_user: <AD_ID>
  become_user: root
  tasks:
    - name: install MySQL Community common
      yum:
        name: /tmp/mysql-community-common-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community libs
      yum:
        name: /tmp/mysql-community-libs-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community libs compact
      yum:
        name: /tmp/mysql-community-libs-compat-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community DebugInfo
      yum:
        name: /tmp/mysql-community-minimal-debuginfo-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community CLIENT
      yum:
        name: /tmp/mysql-community-client-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community embeded compact
      yum:
        name: /tmp/mysql-community-embedded-compat-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community 5.7.9 libs
      yum:
        name: /tmp/mysql-community-libs-5.7.9-1.el7.x86_64.rpm
        state: present
    - name: install MySQL utilities
      yum:
        name: /tmp/mysql-community-devel-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL Community embeded
      yum:
        name: /tmp/mysql-community-embedded-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL community SERVER
      yum:
        name: /tmp/mysql-community-server-5.7.22-1.el7.x86_64.rpm
        state: present
    - name: install MySQL utilities
      yum:
        name: /tmp/mysql-utilities-1.6.5-1.el7.noarch.rpm
        state: present
